# ruby encoding: utf-8
Genre.create(name: 'Biography')
Genre.create(name: 'Children')
Genre.create(name: 'Fantasy')
Genre.create(name: 'Fiction')
Genre.create(name: 'History')
Genre.create(name: 'Horror')
Genre.create(name: 'Humor')
Genre.create(name: 'Memoir')
Genre.create(name: 'Mystery')
Genre.create(name: 'Non-Fiction')
Genre.create(name: 'Poetry')
Genre.create(name: 'Romance')
Genre.create(name: 'Science-Fiction')
Genre.create(name: 'Short Story')
Genre.create(name: 'Thriller')
Genre.create(name: 'Young Adult')
